name: "Check for new upstream release"
description: "Check if given upstream repository has newer release version and trigger new release of this repository"
inputs:
  flavor:
    description: 'Debian/Ubuntu Version'
    required: true
    default: "focal"
  hb_tag:
    description: 'HB Version'
    required: true
runs:
  using: "docker"
  image: docker://smeinecke/handbrake-custom-build:focal
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          cache
        key: "${{ inputs.flavor }}-build-cache-${{ inputs.hb_tag }}"
        restore-keys: |
          "${{ inputs.flavor }}-build-cache-"
    - name: Run build script
      run: ./scripts/build.sh
      shell: bash
      env:
        DEB_FLAVOR: "${{ inputs.flavor }}"
        HB_TAG: "${{ inputs.hb_tag }}"
