# This is a basic workflow that is manually triggered

name: build custom focal handbrake
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: smeinecke/handbrake-custom-build:latest
    container:
      image: ubuntu:focal
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ./scripts/build.sh
