# This is a basic workflow that is manually triggered

name: build custom focal handbrake
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            cache
          key: cache-${{ hashFiles('./scripts/build.sh') }}
          restore-keys: cache-${{ hashFiles('./scripts/build.sh') }}
      - name: Run build script
        run: ./scripts/build.sh
          restore-keys: cache-${{ hashFiles('./scripts/build.sh') }}
      - name: Run build script
        run: ./scripts/build.sh
