# This is a basic workflow that is manually triggered

name: build handbrake on new tag (bullseye)
on:
  workflow_dispatch:
    create:
      tags:
        - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: smeinecke/handbrake-custom-build:bullseye
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set env
        run: echo "HB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run build script
        run: ./scripts/build.sh
        env:
          DEB_FLAVOR: "bullseye"
      - name: Upload deb files
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./*.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb