# This is a basic workflow that is manually triggered

name: repo test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      hb_tag:
        description: 'HandBrake Version Tag'
        default: '1.7.1'
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository_owner }}/handbrake-custom-build:focal"
      options: --privileged --device /dev/fuse
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download release focal
        run: >
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.focal_amd64.deb && \
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.focal_amd64.deb
      - name: Download release jammy
        run: >
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.jammy_amd64.deb && \
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.jammy_amd64.deb
      - name: Download release mantic
        run: >
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.mantic_amd64.deb && \
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.mantic_amd64.deb
      - name: Download release bullseye
        run: >
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb && \
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb
      - name: Download release bookworm
        run: >
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.bookworm_amd64.deb && \
          wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.bookworm_amd64.deb
      - name: Github pages APT repo (focal)
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bookworm
            bullseye
            focal
            jammy
            mantic
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.focal_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.focal_amd64.deb"
          file_target_version: focal
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1
      - name: Github pages APT repo (jammy)
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bookworm
            bullseye
            focal
            jammy
            mantic
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.jammy_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.jammy_amd64.deb"
          file_target_version: jammy
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1
      - name: Github pages APT repo (mantic)
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bookworm
            bullseye
            focal
            jammy
            mantic
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.mantic_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.mantic_amd64.deb"
          file_target_version: mantic
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1
      - name: Github pages APT repo (bullseye)
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bookworm
            bullseye
            focal
            jammy
            mantic
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb"
          file_target_version: bullseye
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1
      - name: Github pages APT repo (bookworm)
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bookworm
            bullseye
            focal
            jammy
            mantic
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.bookworm_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.bookworm_amd64.deb"
          file_target_version: bookworm
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1