# This is a basic workflow that is manually triggered

name: repo test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        type: choice
        description: 'Debian/Ubuntu Version'
        options:
          - 'focal'
          - 'bullseye'
        required: true
      hb_tag:
        description: 'HandBrake Version Tag'
        default: '1.5.1'
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: "smeinecke/handbrake-custom-build:${{ github.event.inputs.flavor }}"
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build script
        run: "wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-${{ github.event.inputs.flavor }}_${{ github.event.inputs.hb_tag }}_amd64.deb && wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-${{ github.event.inputs.flavor }}-cli_${{ github.event.inputs.hb_tag }}_amd64.deb"
      - name: Github pages APT repo
        uses: smeinecke/apt-repo-action@b7e4d4b3535f2c50e42e302384da0177ecc81965
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            ${{ github.event.inputs.flavor }}
          file: |
            "handbrake-${{ github.event.inputs.flavor }}_${{ github.event.inputs.hb_tag }}_amd64.deb"
            "handbrake-${{ github.event.inputs.flavor }}-cli_${{ github.event.inputs.hb_tag }}_amd64.deb"
          file_target_version: ${{ github.event.inputs.flavor }}
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1