# This is a basic workflow that is manually triggered

name: repo test
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      hb_tag:
        description: 'HandBrake Version Tag'
        default: '1.5.1'
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: "smeinecke/handbrake-custom-build:focal"
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download release focal
        run: "wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.focal_amd64.deb && wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.focal_amd64.deb"
      - name: Download release bullseye
        run: "wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb && wget https://github.com/smeinecke/handbrake-deb/releases/download/${{ github.event.inputs.hb_tag }}/handbrake-cli_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb"
      - name: Github pages APT repo
        uses: smeinecke/apt-repo-action@56a3e6c77f27a19abfe47f721ca55ab4a1e25c26
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            focal
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.focal_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.focal_amd64.deb"
          file_target_version: ${{ github.event.inputs.flavor }}
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1
      - name: Github pages APT repo
        uses: smeinecke/apt-repo-action@56a3e6c77f27a19abfe47f721ca55ab4a1e25c26
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: amd64
          repo_supported_version: |
            bullseye
          file: |
            "handbrake_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb"
            "handbrake-cli_${{ github.event.inputs.hb_tag }}.bullseye_amd64.deb"
          file_target_version: ${{ github.event.inputs.flavor }}
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
          debug: 1